/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main
 * Method:    entry_point
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Main_entry_1point
  (JNIEnv *, jclass, jobjectArray);


#ifdef __cplusplus
}
#endif
#endif


int entry_point(int argc, char *argv[]);
